{
 "title": "Cisco Call Manager | System Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"host\",\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hrProcessorTable",
     "query": "from(bucket: \"telegraf\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\t|> filter(fn: (r) => r[\"_measurement\"] == \"hrProcessorTable\")\n\t|> filter(fn: (r) => r[\"_field\"] == \"hrProcessorLoad\")\n\t|> filter(fn: (r) => r[\"source\"] == \"${hostname}\")\n\t|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\t|> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "hrProcessorLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "ICMP Avg Response",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"average_response_ms\")\n    |> filter(fn: (r) => r[\"url\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> filter(fn: (r) => r[\"source\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Total Processes\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"System\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Total Processes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "memory",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"% Mem Used\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "% Mem Used" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "memory",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"% VM Used\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "% VM Used" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Page Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "memory",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"% Page Usage\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "% Page Usage" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "DB Replication",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "number_of_replicates_created_and_state_of_replication",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Number of Replicates Created and State of Replication\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Replicate_State\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Replicate_State" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU $tag_index",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" }
     ],
     "measurement": "hrProcessorTable",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hrProcessorTable\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hrProcessorLoad\")\n  |> filter(fn: (r) => r[\"source\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "hrProcessorLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "CPU (Total)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hrProcessorTable",
     "select": [
      [
       { "params": [ "hrProcessorLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "partition",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Partition\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Total Mbytes\" or r[\"_field\"] == \"Used Mbytes\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Total Mbytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "memory",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Used KBytes\" or r[\"_field\"] == \"Used Swap KBytes\" or r[\"_field\"] == \"Used VM KBytes\" or r[\"_field\"] == \"Total KBytes\" or r[\"_field\"] == \"Total Swap KBytes\" or r[\"_field\"] == \"Total VM KBytes\" or r[\"_field\"] == \"Free KBytes\" or r[\"_field\"] == \"Free Swap KBytes\" or r[\"_field\"] == \"Shared KBytes\" or r[\"_field\"] == \"Cached KBytes\" or r[\"_field\"] == \"Buffers KBytes\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Used KBytes" ], "type": "field" }
      ],
      [
       { "params": [ "Total KBytes" ], "type": "field" }
      ],
      [
       { "params": [ "Total Swap KBytes" ], "type": "field" }
      ],
      [
       { "params": [ "Used Swap KBytes" ], "type": "field" }
      ],
      [
       { "params": [ "Total VM KBytes" ], "type": "field" }
      ],
      [
       { "params": [ "Used VM KBytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_counter: $col",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "network_interface",
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Network Interface\")\n  |> filter(fn: (r) => r[\"instance\"] == \"eth0\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Total Bytes" ], "type": "field" }
      ],
      [
       { "params": [ "Rx Bytes" ], "type": "field" }
      ],
      [
       { "params": [ "Tx Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}