{
 "title": "Cisco Call Manager | Device Registration",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cisco CUCM | Registered Jabber Devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cisco_risport\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"Phone\" and\n    r[\"model\"] == \"Cisco Unified Client Services Framework\"\n    and\n    r[\"status\"] == \"Registered\"\n  )\n  |> group(columns:[\"model\"])\n  |> unique(column: \"model\")\n  |> count()"
    }
   ]
  },
  {
   "title": "Cisco CUCM | Registered Devices by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"cisco_risport\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"Phone\"\n      and\n      r[\"status\"] == \"Registered\"\n  )\n  |> group(columns:[\"model\"])\n  |> unique(column: \"name\")\n  |> keep(columns: [\"_value\", \"_start\",\"_stop\",\"model\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Cisco CUCM | Registered SIP Trunks by Name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"cisco_risport\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"SIPTrunk\"\n      and\n      r[\"status\"] == \"Registered\"\n  )\n  |> group(columns:[\"name\"])\n  |> unique(column: \"model\")\n  |> keep(columns: [\"_value\", \"_start\",\"_stop\",\"name\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Cisco CUCM | Phone Registration Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"cisco_risport\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Phone\")\n  |> filter(fn: (r) => r[\"status\"] == \"Registered\")\n  |> group(columns: [\"model\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Cisco CUCM | Media Resource Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"cisco_risport\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MediaResources\")\n  |> filter(fn: (r) => r[\"status\"] == \"Registered\")\n  |> duplicate(column: \"name\", as: \"name_group\")\n  |> group(columns: [\"name_group\"])\n  |> last()"
    }
   ]
  }
 ]
}