{
 "title": "Cisco Call Manager | SIP Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Trunk",
    "label": "SIP Trunk",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"cisco_perfmon\", tag: \"instance\", predicate: (r) => r._measurement == \"Cisco SIP\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cisco Call Manager | CallsActive",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco SIP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CallsActive\")\n  |> filter(fn: (r) => r[\"instance\"] == \"${Trunk}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cisco Call Manager | CallsInProgress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco SIP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CallsInProgress\")\n  |> filter(fn: (r) => r[\"instance\"] == \"${Trunk}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cisco Call Manager | CallsCompleted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco_perfmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco SIP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CallsCompleted\")\n  |> filter(fn: (r) => r[\"instance\"] == \"${Trunk}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}